config.json
This will allow the mozsearch code to provide customized log/raw links
for files in these repos, rather than just pointing to URLs with
mozilla-central hard-coded in them.
Goes with https://github.com/bill-mccloskey/mozsearch/pull/31
=> Add hg_root values to hg.m.o. trees

comm-central/find-repo-files, mozilla-central/find-repo-files, nss/find-repo-files, whatwg-html/find-repo-files
This makes the behaviour more predictable on Windows, where symlinks may not
be handled properly.
Similar to https://github.com/mozsearch/mozsearch/pull/65 (but no dependency; the PRs can be merged independently).
=> Replace symlinks with a bash script that execs the target

comm-central/find-mc-rev.py
Apparently at some point recently the job type of linux64 debug builds on c-c changed. This updates the script to allow either the old or the new job type.
(This fixes the problem for me locally but I haven't tested a deployment with it yet)
=> Allow job types of build-linux64/debug as valid c-c target jobs.

help.html
There's a similar snippet in [a test file in the mozsearch repository](https://github.com/mozsearch/mozsearch/blob/master/tests/help.html). Should it be updated as well?
=> Mention Rust indexing in help page

nss/setup, whatwg-html/setup
The mozilla-central and comm-central repos already have these checks;
for consistency and additional bandwidth davings during local development
we can do it for these repos as well.
=> Avoid redownload of nss and whatwg tarballs

mozilla-central/upload
Running `git gc` on gecko-dev brought the size down from ~11G
to ~6G and gecko-blame shrunk from ~14G to ~1.7G. This reduces
indexer runtime and data transfer noticeably. This patch
monitors the size of the tarballs and re-compresses the repos
if they get too big.
=> Re-compress the gecko-dev and gecko-blame repos periodically.

mozilla-central/setup
Use the new analysis-merging script to do the merge, which will
union the symbols properly for source lines.
This depends on https://github.com/mozsearch/mozsearch/pull/145
=> Bug 1490521 - Merge C++ analysis files better

config.json
We need https://github.com/mozsearch/mozsearch/pull/159 for this.
This fixes all links except the nss one because I don't know which git repo
we're using. I've verified that all git links are working now except that one
which still points to gecko-dev.
=> Update config.json with GitHub repos.

mozilla-central/setup
Instead of preferring generated sources from some platforms, compare
all the platform-specific variants of the generated files. If they match,
then keep a single copy of the file as before. If they don't match, put
each platform variant into a platform-specific subdir of the objdir/ and
under `analysis/__GENERATED__/`.
=> Improve handling of generated sources

comm-central/setup, mozilla-beta/build, mozilla-beta/find-repo-files, mozilla-beta/setup, mozilla-beta/upload, mozilla-central/setup, mozilla-esr60/build, mozilla-esr60/find-repo-files, mozilla-esr60/setup, mozilla-esr60/upload, mozilla-release/build, mozilla-release/find-repo-files, mozilla-release/setup, mozilla-release/upload, mozilla-releases.json, shared/fetch-gecko-dev.sh
These patches add mozilla-{beta,release,esr60} repos, but do so in a new config file. This will allow us to index these trees on a separate indexer/webserver instance than the one that does the existing repos listed in config.json. See https://bugzilla.mozilla.org/show_bug.cgi?id=1282123#c2 for some context.
These patches have no dependencies in that they should be able to land without breaking anything.
=> Add a mozilla-releases.json config file

nss/setup
Now that the tarball in S3 has no uncommitted changes this reset is no longer needed.
=> Bug 1548123 - Remove unnecessary git reset

mozilla-beta/setup, mozilla-central/setup, shared/fetch-tc-artifacts.sh, shared/process-tc-artifacts.sh
This obsoletes #8. Now we get the src/analysis data from taskcluster rather than installing it on the indexer instance. This ensures that the data we get is in sync with the anaylsis data for the rest of m-c.
This depends on the m-c patches on bug 1545968 which are pending review.
=> Bug 1545968 - Download and unpack the rust stdlib src and analysis data.

README.md
This includes removing the historical note which was more of a distraction,
but for posterity, :kats referenced
https://bugzilla.mozilla.org/show_bug.cgi?id=1494947 and that provides
useful context.
=> Update reverted times, correct typo, improve rationale.

nss/setup
Per my email replying to the searchfox errors from the config.json run, it turns out our NSPR tarball includes configuration data that hardcodes the /index path.  I mentioned a potential symlink mitigation in there, but I've not undertaken it since I think it's better for NSS to just do the hg checkout every time.  This isn't appropriate for repositories with more turnover, but NSPR has very little turnover and the mozilla hg server has optimized bundle magic.
Please feel free to merge this if you're okay with it, as tomorrow's config.json build will be broken without this.
=> Bug 1567724 - Correct NSS build regression. r=kats

config.json
We need this so that https://searchfox.org's default search box is mozilla-central.  This
depends on https://github.com/mozsearch/mozsearch/pull/240.
=> Bug 1580266 - Specify mozilla-central as our default tree for help.html purposes. r=kats

shared/process-gecko-analysis.sh, shared/process-tc-artifacts.sh
Depends on https://github.com/mozsearch/mozsearch/pull/251.
This changes the process-gecko-analysis.sh callers to process rust analysis data on a per-platform basis and inhibits the all-platforms invocation of rust-analyze.sh by mkindex.sh by dropping the hacky sentinel file.
=> Bug 1583031 - Have rust analysis run (optionally) per-platform

nss/setup, shared/fetch-hg-map.sh
The mapper files are not .tar.bz2 files with paths that look like:
- build/conversion/nss-dev/.hg/git-mapfile
- ./build/conversion/beagle/.hg/git-mapfile (This is the gecko-dev mapping,
I'm really hoping beagle is a codename and not the wrong source tree!)
Since we don't care about the paths and there's a single file, we can
use the "-O" option to tar to make it extract the contents to stdout.  So
the tar invocation becomes `-xOj` where x is extract and j is bz2
decompression.
I've tested this locally.
=> Bug 1595492 - Update mapper downloading.

config.json
Reverts mozsearch/mozsearch-mozilla#62
=> Revert "Bug 1596107 - Temporarily disable "ash" branch after taskcluster migration due to no recent builds"

mozilla-mobile/setup
This is for https://bugzilla.mozilla.org/show_bug.cgi?id=1596846 which is about modifying the git repo you created in https://bugzilla.mozilla.org/show_bug.cgi?id=1530798.  I think I inferred the right actions to cargo cult, sans the call to init the nested submodule, but honestly my git submodule "expertise" is a bit rusty.
My intent here is to make sure that if our submodules gain any new submodules, they get properly initialized.  I understand this to be generally safe and correct.  The thing I'm a little concerned about is really the interaction with "--remote" in terms of the nested submodules.  I don't think I'm changing the semantics around that, but it appears like FirefoxReality's submodule is a specific revision to be checked out and my fear would be if we end up just always …
=> Bug 1596846 - Make sure to init new nested submodules as they appear. r=kats

mozilla-mobile/setup
@staktrace I'm going to merge this as a bustage fix right now, but I'm very interested in your thoughts here.  I'm keeping a copy of the unhappy tarball locally and have also replicated it to the backups/ directory at https://s3-us-west-2.amazonaws.com/searchfox.repositories/backups/mozilla-mobile.tar so interested parties can do some investigation of the situation, although it seems possible that what's on github may change or the github servers may get updated or something.
=> Bug 1596846 - bustage fix related to updates. r=asuth, a=bustage

shared/collapse-generated-files.sh, shared/process-tc-artifacts.sh
I tested the concept on one of the web-servers but haven't run with it.
=> Bug 1619363 - Be case-insensitive when normalizing windows z: paths. r=kats

config.json, mozilla-archived.json, mozilla-releases.json
I created a new target group called `mozilla-archived-target`, ran the indexer on this config, and hooked it all up, so it's live. Going to https://searchfox.org/mozilla-esr60/source right now will serve the content from the `mozilla-archived` web-server instance. I'll update docs and add more ESR repos in separate patches.
=> Bug 1617567 - Move ESR60 to a new mozilla-archived config.

mozilla-central/setup
This is the first step in adding the new ESRs, as it will create the necessary named branches in the gecko-dev and gecko-blame tarballs. Once this runs on an release indexer and the resulting tarballs are uploaded into S3, I can make the final change which adds the new repos to mozilla-archived.json.
=> Bug 1617567 - Have the m-c indexer build blame for more ESRs

mozilla-central/setup
This reverts commit 29627e2632864520e721713ad35b03f6c2245f53, it's not doing what I expect it to.
=> Revert "Bug 1617567 - Have the m-c indexer build blame for more ESRs"

glean/build
I'd like to keep mozilla-central `build` failures fatal, so I don't want to catch errors at the call site for this build script. Instead, let's make the glean repo non-fatal. I haven't actually tested this patch in that commands later in the indexing run might fail due to not finding analysis files or something.
=> Make a glean build failure non-fatal

nss/setup, shared/checkout-gecko-repos.sh
This makes us pull directly from source-of-truth repos instead of gecko-dev.
=> Pull m-c repos using cinnabar

find-repo-files.py
This adds a dependency on `six` which the indexer already has due
to boto3 relying on it.
=> Bug 1616362 - Run python-modernize on all the python scripts

mozilla-central/check, shared/process-tc-artifacts.sh
I moved the generated extraction up so that generated-$PLATFORM would already be created by the time the rust stdlib move stuff happens.
Again, feel free to merge this with the other and change the check as needed.  Also of course feel free to not land and request changes and all that good stuff.  I just won't be up before the indexing runs start tomorrow morning :)
=> Bug 1641079 - Make `__GENERATED__/__RUST__` work. r=kats

mozilla-central/setup
We were updating the branches in gecko-dev from the "origin" remote which we're no longer pulling updates to. I should have just deleted that remote when I was migrating to cinnabar, as that would have caused this line to throw an error which I would have caught. But anyhoo, this should fix it so we update from cinnabar. I'm also manually updating the blame repo and will push it to S3 so tomorrow's indexer don't have to do as much work. I've backed up the current tarballs in case I screw up.
=> Bug 1641679 - Update gecko-dev branches from the correct remote.

mozilla-central/check, shared/process-tc-artifacts.sh
Per discussion in https://github.com/mozsearch/mozsearch/pull/348 normalize
paths to:
- `__GENERATED__/__linux64__/__RUST_STDLIB__/...` for stdlib
- `__GENERATED__/__linux64__/__RUST_BUILD_SCRIPT__/webrender/shaders.rs` for crate-generated
=> Bug 1646069 - Normalize rust build script output paths. r=kats

mozilla-central/check
I ran `~/mozsearch/infrastructure/web-server-check.sh ~/config ~/index ~` on the "asuth" server (which I'm leaving up for now so you can check stuff and should feel free to login to) and here's the excerpt of that specific check which covers both filesystem and network checks.
In the patch I only check linux and do some hand-waving about that because I don't want us to break if windows takes a day off, but we can check the other platforms too or all of them, etc.  I'm fine with whatever, really, just didn't want to make the daily runs brittle for no reason.  (Also, I'm assuming the shaders thing will stick around for a while?)
```
+ /home/ubuntu/mozsearch/scripts/check-helper.sh filesystem http://localhost/ __GENERATED__/__linux64__/__RUST_BUILD_SCRIPT__/webrender/shaders.rs …
```
=> Bug 1646069 - Add webrender shaders.rs check. r=kats

help.html
=> Bug 1650538 - Add link to comm-esr78 on main help page

config.json, shared/fetch-tc-artifacts.sh
This adds a wpt_root and downloads the test and WPT info in an optional fashion.
=> Bug 1653986 - Download test info for gecko-dev builds and define a wpt_root for m-c. r=kats

shared/fetch-tc-artifacts.sh
The hookup for this is simple, but as covered in https://bugzilla.mozilla.org/show_bug.cgi?id=1566874 the coverage bot/taskcluster hookup isn't currently reliably timely enough for us to demand the same revision Searchfox was built against.  This is probably better than nothing for now?
=> Bug 1566874 - Initial coverage hookup. r=kats

mozilla-central/check, shared/process-tc-artifacts.sh
(Just need one review, changes are relatively straightforward)
=> Bug 1672405 - Support changed folder structure in rust-src tarball in rust 1.47 and up.

shared/process-tc-artifacts.sh
In rust 1.47 the library is indeed in /library, but there's also
stuff under /src (just `llvm-project/libunwind`).
Since it's not empty we were copying it instead of the rust stdlib.
We could copy both instead, though that might need adding wildcards and
complicating the script. This fixes the indexing error and we can do
that in a follow-up, though it's not clear that having libunwind gives
us much benefit.
=> Fix process-tc-artifacts.sh for rust 1.47 stdlib.

mingw-moz/setup
I tested by running the command in question on today's release2 indexer which is still going
=> Bug 1684371 - Update yq syntax for yq version 4.2.0

mozilla-central/rebuild-blame.sh
This script currently isn't invoked from anywhere but it can be run
manually to regenerate the gecko-blame repo. Future changes might
make this easier to run in an unattended fashion.
=> Bug 1683563 - Add a script that facilitates rebuilding gecko-blame

kaios/upload
This copies over the gc heuristics from the mozilla-central upload
script to kaios as well, since it suffers from the same problem
where the tarballs can grow quite large over time.
=> Bug 1684386 - Pack the kaios tarballs more

config4.json, glean/setup, glean/upload, mozilla-build/setup, mozilla-build/upload, whatwg-html/setup, whatwg-html/upload
This makes it so that all the repos listed in config4.json extract
their git tarballs into a `git` folder and their blame tarballs into
a `blame` folder. This is good for consistency and scriptability.
Also the tarball names are now `<repo-name>.tar` for the git tarball
and `<repo-name-blame>.tar` for the blame tarball.
=> Bug 1690181 - Normalize the config4.json repos git/blame folders

comm-central/setup, mozilla-central/upload, nss/setup, nss/upload, shared/checkout-gecko-repos.sh, shared/fetch-gecko-tarball.sh
All the other repos have their git repo in `<foo>.tar` and
blame repo in `<foo>-blame.tar`. gecko-dev is unique in using
`gecko-dev.tar` and `gecko-blame.tar`. This patch brings gecko
in line with the other repos, by changing the git tarball to
be `gecko.tar`. Note that the folder inside is still `gecko-dev`;
eventually it will be renamed to `git` to match other
repositories but that'll happen when I'm more in the mood to
manually download and re-upload a 10G tarball.
=> Bug 1690181 - Rename gecko-dev.tar to gecko.tar

shared/rebuild-blame.sh
- Silence curl's logging spew
- Do an aggressive gc after building the blame repo, which
in particular produces better delta compression and can result in
a significantly smaller repo
=> Bug 1683563 - Minor tweaks to the rebuild-blame script

config4.json, mozilla-central/reblame, mozilla-central/setup, mozilla-pine/build, mozilla-pine/repo_files.py, mozilla-pine/setup, shared/checkout-gecko-repos.sh
I know for "ash" we just called it "ash", but it seems like having the
"mozilla-" prefix better conveys that's it's an m-c branch and that it
uses the same underlying gecko repo/etc. while avoiding the problems
of using "mozilla-central" as a prefix like in "mozilla-central-pine".
I put this in config4 because config4 currently has the fastest indexing
time per my analysis at
https://bugzilla.mozilla.org/show_bug.cgi?id=1712622#c1 and our disk
usage is also relatively low, at 41G / 240G
I'm intentionally leaving this off the help.html listing for now per
discussion with the branch owners.
=> Bug 1712622 - Index the m-c pine project branch. r=kats

mozilla-pine/build
When I transitioned from skipping the analysis to building it, I forgot
to update the build script from the no-op build script.
=> Bug 1712622 - enable pine semantic indexing in build script

mozilla-central/check
In bug 1711648 the Box2d type was removed from the webrender
bindings code, so this check started failing. Updating it to
reference a different type from the same file that is less
likely to be deleted.
=> Bug 1722889 - Update check target to one that still exists

l10n/upload, mozilla-mobile/upload
For l10n, the submodules are cinnabar repos and need
regular cinnabar fsck runs to avoid warnings, so let's do
that.
Even ignoring the cinnabar warnings, doing regular gc on
the submodules is a good idea, so we do it for mozilla-mobile
as well. In that case there's no cinnabar submodules so
we can use the more normal foreach subcommand rather than
manually looping through the submodules.
=> Bug 1716167 - Run maintenance for submodules as well

mozilla-central/checks/snapshots/check_glob@rust__build__webrender_shader__json.snap, mozilla-central/checks/snapshots/check_glob@rust__first_party__webrender__moz2d__def__json.snap, mozilla-central/checks/snapshots/check_glob@rust__stdlib__btreemap__def__json.snap, mozilla-central/checks/snapshots/check_glob@rust__third_party__euclid__def__json.snap, mozilla-central/checks/snapshots/check_glob@rust__xpidl__nsichannel__json.snap
Test expectations re-derived updated after applying
https://github.com/mozsearch/mozsearch/pull/446
This maintained input JSON key ordering.
=> Bug 1729178 - Enable serde_json preserve_order feature

mozilla-mobile/setup
The follow bad thing happened:
```
+ pushd /mnt/index-scratch/mozilla-mobile/git
/mnt/index-scratch/mozilla-mobile/git ~
+ git submodule update --remote
From https://github.com/mozilla-mobile/android-components
1f0e0c8b2e..2d152a477f  main       -> origin/main
Submodule path 'android-components': checked out '2d152a477f3c1ca162304db466a504753c0c9f24'
From https://github.com/mozilla-mobile/firefox-ios
* [new branch]          lm/#9422-Epic-branch-bottom-searchbar -> origin/lm/#9422-Epic-branch-bottom-searchbar
a62962279..df6c2db93  update-br-new-xcode-version -> origin/update-br-new-xcode-version
From https://github.com/mozilla-mobile/focus-android
3887ed02..0d874021  main                    -> origin/main
error: cannot lock ref 'refs/remotes/origin/mergify': …
```
=> Unbreak mozilla-mobile, probably

just-mc.json
In particular, in cases where I want to update the test expectations
for m-c, it's nice to be able to do this without having to create a new
branch, etc.
I'd previously entertained having a filter mechanism for this, and I
think I may even have patches for that, but this seems more
straightforward in terms of understanding what's happening with tags in
the AWS instance list, etc.
=> Add a config that's just mozilla-central for expedited testing.

mozilla-central/checks/snapshots/check_glob@xpidl__xpctest_params__def_testOctet__html.snap, mozilla-central/checks/snapshots/check_glob@xpidl__xpctest_params__def_testOctet__json.snap
This is from following the steps documented at
https://github.com/mozsearch/mozsearch/blob/master/docs/testing-checks.md#updating-checks-on-a-stopped-aws-indexer-due-to-local-disk-check-failure
after triggering a just-mc run.
I have not added extra checks for the attributes case because my chicken
nuggets are done and I would like to eat them and this check is a pretty
good smoke test check given that it's consistent with our checks in the
tests repo too and all failures would be correlated!
=> Bug 1759064 - Update checks for multiple source recs

mozilla-esr17/repo_files.py, mozilla-esr31/repo_files.py, mozilla-esr45/repo_files.py, mozilla-esr60/repo_files.py, mozilla-esr68/repo_files.py
I use the IDL filtering mechanism here to disable XPIDL analysis on older ESR
branches for 2 reasons:
1. ESR45, ESR60, ESR68 all have in-tree versions that we'll try to use but
which aren't legal Python 3 code, which means when we try and use them we'll
throw once per file.  The python 3 compatible versions don't indicate
they want to use python3 on the first line which meant a more involved
attempt at shell detection.  And handling the error in the Python still
would potentially result in N error messages if we have any error messages.
2. ESR17 and ESR31 both pre-date having an xpidl.py in that path we look for
it, but it seems likely the modern parser is more likely to encounter
problems because of this but we don't really care.  It's more of an accident
that we try and parse the IDL …
=> Bug 1759930 - Filter out IDL files for ESR builds with pre-python3 xpidl.py

help.html
They won't be needed with the upcoming CSS changes.
=> Remove style attributes from links.

wubkat/repo_files.py
js-analyze was trying to parse a metal `.inc` shader which is not a
thing that will go well.  (I think it was trying to parse it as XUL,
because that's what .inc files historically were in m-c, but still,
it appropriately did not go well.)
It may be appropriate to let a config.json specify that JS failures are
non-fatal, or even to make JS analysis failures non-fatal by default.
It's possible for the LSIF support we may move to effectively doing
this.
=> Bug 1771804 - Only treat .js files as JS

config5.json, wubkat/setup
Ubuntu 22.04 has been explicitly supported for ~2 months now it seems per
https://searchfox.org/wubkat/commit/aa960b1a0c7b980efdbc66718239a449b5966a0c
so we should be able to go back to using that.  This will fix current tree
breakage because "unifdef" isn't installed and should ideally generally
improve wubkat stability.
I'm reverting the behavior from "continue" to "halt" but we probably want
an annotation on the root of the config to enable "terminate" rather than
just what our de facto current approach is of "stop" (we shutdown, which
results in the instance being "stopped").
=> Bug 1783459 - Try switching wubkat to in-tree apt deps, revert to halt

shared/process-tc-artifacts.sh
I had already dealt with `+` systematically by having us use "-E" so my attempt to make sure sed was happy with `\+` actually made things worse, whoops!
=> Bug 1792322 - Actually, we can just use `+` in sed because of `-E`

wubkat/last-successful-build-to-git-commit.sh, wubkat/setup
All the hard work here was done by dpino at
https://gist.github.com/dpino/b324320652bb8b758acde123f9a3dbdc where this revision is sourced from.  We specifically are using: https://gist.githubusercontent.com/dpino/b324320652bb8b758acde123f9a3dbdc/raw/87d75cfe4ff8aa8a4d2fd7f86dfc507f18cd58fa/last-successful-build-to-git-commit.sh
I've annotated the script itself with equivalent information, but there is a potential for it to get lost if we update the script (although we should try not to).
=> Bug 1786930 - Build wubkat using last successful revision.

mozilla-central/checks/inputs/analysis/xpidl/xpctest_params__def_testOctet__html, mozilla-central/checks/inputs/analysis/xpidl/xpctest_params__def_testOctet__json, mozilla-central/checks/snapshots/analysis/xpidl/check_glob@xpctest_params__def_testOctet__html.snap, mozilla-central/checks/snapshots/analysis/xpidl/check_glob@xpctest_params__def_testOctet__json.snap
Identical changes to the tests repo where we needed to explicitly provide the full identifier name for XPIDL members now.
=> Bug 1776522 - Move from ANALYSIS_DATA to SYM_INFO for context-menu.

glean/build
This isn't working now anyway, because the nightly rust compiler has dropped support for save-analysis. And without that there's no point trying to compile.
=> Stop trying to build glean

shared/process-tc-artifacts.sh
Instead of a bespoke directory. This will make it easier to choose one vs the other.
For now this doesn't change behavior.
=> taskcluster: Extract scip index in the platform-specific objdir

mozilla-esr102/setup, shared/fetch-tc-artifacts.sh
The scip downloads were only added in FF 109, and we run this code on ESR 102 which doesn't have the scip files. So let's make it optional to prevent getting warnings all the time.
=> No bug - make scip files optional on esr102

just-llvm.json, llvm/build
This also adds a "just-llvm.json" configuration file along the lines of "just-mc.json" for the benefit of faster iteration if trying out C++ indexer improvements against a non-trivial codebase.  config4 is quite heavy-weight right now, so it's desirable to avoid building everything else.  Also LLVM potentially may make a faster C++ iteration target than mozilla-central in many cases since it can be triggered in a single go without needing to trigger a "try" job, etc.
=> Bug 1852405 - Perform semantic C++ indexing of LLVM

llvm/build
Instead of building into a "build" subdir, use the explicit $OBJDIR that searchfox expects.
This improves upon https://github.com/mozsearch/mozsearch-mozilla/pull/210
=> Bug 1852405 - Build LLVM using an explicit objdir instead of "build" subdir.

.gitignore, config1.json, config2.json, config3.json, config4.json, config5.json, just-mc.json, mozilla-central/build, shared/process-tc-artifacts.sh
A change to the config file format in https://github.com/mozsearch/mozsearch/pull/663 requires all the config files to have a scip_subtrees JSON property.  This adds that plus replaces use of rust-indexer with scip-indexer.  Also we'll index some python stuff in m-c.
=> Bug 1859373 - Use scip-indexer for rust indexing, plus index the m-c python tree

shared/fetch-tc-artifacts.sh, shared/process-tc-artifacts.sh
Up on dev.searchfox.org for testing already, see eg. [this search for org.mozilla.geckoview.GeckoSession.PromptDelegate.AutocompleteRequest](https://dev.searchfox.org/mozilla-central/search?q=symbol:S_java_java_org%2Fmozilla%2Fgeckoview%2FGeckoSession%23PromptDelegate%23AutocompleteRequest%23) which returns Java and Kotlin files.
Marking as draft until I get the relevant changes reviewed and merged into mozilla-central.
=> Use java/kotlin semanticdb content from mozilla-central

shared/fetch-tc-artifacts.sh
This reverts commit d8202392c2847c1e01d59cb34a5608f621312f85.
Now that mozilla-central has ios searchfox tasks, we shouldn't need to exclude those.
=> Revert "Avoid warnings about missing ios on non-cedar branches"

shared/fetch-tc-artifacts.sh
Preparation part for https://bugzilla.mozilla.org/show_bug.cgi?id=1895316
This downloads `chrome-map.json` from ccov task.
the processing part is addressed in mozsearch repository.
=> Bug 1895316 - Fetch chrome-map.json

shared/fetch-tc-artifacts.sh
ccov and chrome-map might not always be available for non-m-c branch
=> Make chrome-map.json optional

shared/fetch-tc-artifacts.sh
depends on https://bugzilla.mozilla.org/show_bug.cgi?id=1895989
bug 1895989 will add `chrome-map.json` to the artifact of searchfox(idx) job, for each OS.
This fetches `chrome-map.json` from all OSes.
=> Bug 1896165 - Fetch chrome-map.json files from searchfox jobs

comm-central/repo_files.py, kaios/repo_files.py, mozilla-beta/repo_files.py, mozilla-cedar/repo_files.py, mozilla-central/repo_files.py, mozilla-elm/repo_files.py, mozilla-esr102/repo_files.py, mozilla-esr115/repo_files.py, mozilla-esr17/repo_files.py, mozilla-esr31/repo_files.py, mozilla-esr45/repo_files.py, mozilla-esr60/repo_files.py, mozilla-esr68/repo_files.py, mozilla-esr78/repo_files.py, mozilla-esr91/repo_files.py, mozilla-release/repo_files.py
Given there are so many HTML files in WPT, and the main purpose here for indexing HTML is to linkify chrome/resource URLs, which won't appear in WPT files, I'll exclude them for now.
We can revisit this once the crossref gets chunked and parallelized, and made capable of handling more files with less RAM usage
=> Exclude WPT from HTML indexing

shared/fetch-tc-artifacts.sh
`macosx64-aarch64` is available only from 128
=> Do not warn when macosx64-aarch64 analysis is missing

shared/fetch-tc-artifacts.sh
ios may not exist on older branch
fixes warning in esr115
=> Do not warn when ios analysis file is missing

config5.json
depends on https://github.com/mozsearch/mozsearch/pull/736
=> Add ignore_missing_path_prefixes config for wubkat and graphviz

config4.json
for https://bugzilla.mozilla.org/show_bug.cgi?id=1899073
=> Bug 1899073 - Add ignore_missing_path_prefixes config for llvm

config5.json, graphviz/build, graphviz/setup
for https://bugzilla.mozilla.org/show_bug.cgi?id=1899642
depends on https://github.com/mozsearch/mozsearch/pull/741
This does:
* use ld-wrapper added by https://github.com/mozsearch/mozsearch/pull/741
* fix the git URL, which had been causing the redirection warning
=> Bug 1899642 - Use ld-wrapper, and fix git URL

graphviz/setup
The Graphviz submodules are only relevant to users building on Windows platforms.
=> graphviz: Remove submodule steps

mozilla-beta/repo_files.py, mozilla-cedar/repo_files.py, mozilla-central/repo_files.py, mozilla-cypress/repo_files.py, mozilla-elm/repo_files.py, mozilla-esr115/repo_files.py, mozilla-esr128/repo_files.py, mozilla-release/repo_files.py
This changes the m-c repo_files to ignore tools/ts added by https://bugzilla.mozilla.org/show_bug.cgi?id=1895418 which caused breakage.  This also propagates the updated repo_files to the other actively indexed m-c trees which includes propagation of the CSS2 properties which seems to be on all branches so it's okay to add.
=> Bug 1416899 - Update WebIDL filters to handle tools/ts, missed dirs

mozilla-esr115/repo_files.py
for https://bugzilla.mozilla.org/show_bug.cgi?id=1904670
`WebIDL.py` is not compatible on ESR115 due to filename data representation difference,
which causes many warnings, and also it fails to find the binding C++ file.
the WebIDL indexing should be disabled on ESR115 at least for now.
Other options would be either:
* make `webidl-analyze.py` compatible with this version, or
* always download `WebIDL.py` from mozilla-central
but I guess we can leave it to other bug.
=> Bug 1904670 - Do not index WebIDL in ESR115

config5.json, just-graphviz.json
This also adds just-graphviz.json which matches the `make build-graphviz-repo` target I added to the Makefile a while ago that requires it but that I forgot to land.  The rationale for these files over the jq filtering approach has been that the jq approach really only works for local indexing runs right now since the indexer does not know how to perform an equivalent step, but I've often thought about adding an equivalent step.  That said, the individual files also allow us to customize the web-server instance type we use which should usually not be the same tier as if the whole config was run.
=> Bug 1904890 - Don't walk graphviz submodules.

mozilla-central/setup
I tested this locally in the shell and it did the right thing, but did not locally do a config1 build.  I'm going to land this and re-trigger config1 immediately and will keep an eye on it.
=> Bug 1909053 - Handle a 404 on COV_TASKID rather than breaking.

config4.json
Our LLVM semantic build also uses CMake and so the change from CMakeTmp to CMakeScratch is also necessary for LLVM in config4 too.
=> Bug 1922408 - update LLVM cmake ignore paths like webkit

wubkat/last-successful-build-to-git-commit.sh
:padenot noticed the builds are old and it seems it's due to the builder name changing.
=> wubkat bustage fix: fix builder name

config4.json, l10n/setup, l10n/upload
I've locally run the steps from
https://github.com/mozsearch/mozsearch/blob/master/docs/newrepo.md for https://github.com/mozilla-l10n/firefox-l10n and created firefox-l10n git and blame lz4 tarballs.  I locally have tested that this works by creating a just-l10n.json config and "build-l10n-repo" target and run with that to verify I didn't mess up anything obvious, but I won't land those changes because this is not a tree that justifies having that; we should just do the dynamic thing so we can specify a config file and a tree in that config file if we want.
=> Bug 1900534 - Switch l10n repo to https://github.com/mozilla-l10n/firefox-l10n

shared/fetch-tc-artifacts.sh
for https://bugzilla.mozilla.org/show_bug.cgi?id=1458882
the `trees.json` URL is going to be added by the bug's patch.
=> Bug 1458882 - Fetch doc trees.json

shared/process-gecko-analysis.sh
This is a part of https://bugzilla.mozilla.org/show_bug.cgi?id=1942757
With the https://github.com/mozsearch/mozsearch/pull/860 patch stack, the files in objdir are all reflected to the output.
The rust-analyzed file is created there for historical reason and it's no longer necessary.
=> Bug 1942757 - Stop creating the rust-analyzed file

mozilla-central/build, mozsearch/build
This is the counterpart of https://github.com/mozsearch/mozsearch/commit/9ec3c6b0.
=> Use scip-python from PATH instead of using mise

config2.json
This is a very common error to make when copying-and-pasting, and I say this based on definitely having made this error this time and before, but also from having reviewed/used various ESR patches contributed.
We already have an essential transformation step in `generate-config.sh` without which the config file will not have usable paths, and this is a situation where jq can easily help us do the numbering.  The question is then whether we remove "codesearch_port" from the authored config files or instead put "auto" in place to help make it clear what we expect to happen downstream in the file's lifecycle.
=> Bug 1890435 - Correct firefox-esr115 codesearch_port copy-and-paste error

firefox-beta/repo_files.py, firefox-main/repo_files.py, firefox-release/repo_files.py, mozilla-beta/repo_files.py, mozilla-cedar/repo_files.py, mozilla-central/repo_files.py, mozilla-cypress/repo_files.py, mozilla-elm/repo_files.py, mozilla-release/repo_files.py
for https://bugzilla.mozilla.org/show_bug.cgi?id=1986051 and https://github.com/mozsearch/mozsearch/pull/897
This does:
* add `CSSStyleProperties.webidl`, which is the new filename of `CSS2Properties.webidl`, to the file list, for each non-esr branches
This can be removed once all non-esr branches receive the [bug 1919582](https://bugzilla.mozilla.org/show_bug.cgi?id=1919582) changes.
=> Bug 1986051 - Add CSSStyleProperties.webidl to the file list.
