mozsearch/mozsearch-mozilla

mozilla-central/setup
nss/setup

I'm going to merge this as searchfox is broken without it.

Update mapper URLs

---

config.json

Update config.json with NSS github repo

---

mozilla-central/setup

There's already a bugzilla task on Taskcluster that generates this, I didn't even have to do anything for that

Bug 1448334 - Download the normalized bugzilla-components file for m-c.

---

mozilla-central/setup

Needs bug 1530016 to merge to m-c before merging this.

Bug 1500941 - Add android-armv7 indexing

---

help.html

Fixes https://bugzilla.mozilla.org/show_bug.cgi?id=1538302

Make it more obvious where the sourcecode is located

---

config.json
mozilla-releases.json

DXR for comm-central is broken so I didn't include that one

Bug 1341203 - Add DXR links for various repos

---

README.md

I wrote some basic stuff but couldn't think of much else that would be useful to say. If you have suggestions on what else to put in here I'm all ears. If not I can always add more stuff later as needed.

Bug 1551082 - Add some docs for mozsearch-mozilla

---

mozilla-beta/setup
mozilla-central/setup
mozilla-esr68/build
mozilla-esr68/setup
mozilla-release/setup
shared/fetch-tc-artifacts.sh
shared/process-tc-artifacts.sh

PR includes patch from #49 because it applies on top of that.

Index rustlib

---

README.md

I wrote these up a little ways back, but the info still seems useful, if only for me.

add some diagnostic tips

---

config.json
help.html
mozilla-build/build
mozilla-build/find-repo-files
mozilla-build/setup
mozilla-build/upload

This depends on https://github.com/mozsearch/mozsearch/pull/263.

Index mozilla-build.

---

config.json
glean/build
glean/find-repo-files
glean/setup
glean/upload
help.html

Glean is the new Telemetry framework, written in Rust with
platform-specific layers on top (currently Kotlin, Swift and Python are
supported).
/cc @emilio

Add Glean to the index

---

mozilla-central/setup

Re-landing after manually updating the blame repo.

Bug 1617567 - Have the m-c indexer build blame for more ESRs

---

mozilla-archived.json
mozilla-esr17/build
mozilla-esr17/find-repo-files
mozilla-esr17/setup
mozilla-esr31/build
mozilla-esr31/find-repo-files
mozilla-esr31/setup
mozilla-esr45/build
mozilla-esr45/find-repo-files
mozilla-esr45/setup

Bug 1617567 - Add additional ESR repos to the mozilla-archived config

---

find-repo-files.py
shared/resolve-gecko-revs.sh

Equivalent to https://github.com/mozsearch/mozsearch/pull/324 but for the config repo.

Execute python scripts directly using shebang

---

comm-esr60/build
comm-esr60/find-repo-files
comm-esr60/setup
comm-esr60/upload
comm-esr68/build
comm-esr68/find-repo-files
comm-esr68/setup
comm-esr68/upload
config.json
ecma262/build
ecma262/find-repo-files
ecma262/setup
ecma262/upload
help.html
mozilla-archived.json
mozilla-releases.json

I uploaded the necessary tarballs to S3 and updated the forwarding rules in the release lead balancer for the esr repos.

More repos

---

config4.json
help.html
rust/build
rust/setup
rust/upload

Requires https://github.com/mozsearch/mozsearch/pull/383

Bug 958852 - Add the rust repo.

---

shared/fetch-tc-artifacts.sh

I also updated the coverage comment which was a little bit-rotted.

Bug 1691724 - Failover to using "latest" for bugzilla component mappings when the indexed revision artifact isn't there. r=kats

---

comm-central/reblame
comm-central/setup
comm-central/upload
config1.json
mozilla-mobile/setup
mozilla-mobile/upload

Merging these patches will need to be accompanied with actual changes to the tarballs, which I will do once the patches are r+'d.

Normalize folder names in comm-central and mozilla-mobile

---

shared/rebuild-blame.sh

The aggressive gc we were using before was useful in significantly
reducing the size of the blame tarballs. However, we can achieve
the same effect with an explicit repack, where we control the memory
usage better to avoid OOMs. See comments in the code for details.

Bug 1683563 - Flip-flop back to a git repack

---

config2.json
help.html
mozilla-esr91/build
mozilla-esr91/repo_files.py
mozilla-esr91/setup
mozilla-esr91/upload

This is phase 2 of adding esr91.

Bug 1717535 - Add esr91 to config2 and the config1 help.html listing.

---

mozilla-mobile/setup

See comments in the pull request and on the bug for context.

Bug 1754125 - Always run git gc for mozilla-mobile

---

help.html
mozilla-esr68/build
mozilla-esr68/setup
mozilla-esr68/upload

Bug 1759930 - Remove semantic analysis for frozen/static ESR68.

---

help.html

* Split into paragraphs for easier reading
* Link to RE2 documentation on regex syntax.
https://bugzilla.mozilla.org/show_bug.cgi?id=1766096

Bug 1766096 - Improve query language docs a bit

---

config5.json
wubkat/build
wubkat/reblame
wubkat/setup
wubkat/upload

Test run got to 99% before gi-docgen experienced a problem.  Let's try this with gi-docgen stubbed and test the upload automation by running this as release5.

Bug 1771804 - Add wubkat tree

---

help.html

This may be a candidate for automated templating soon...

Bug 1792490 - Update help.html to reflect ESR91 changes

---

wubkat/setup

Bug 1786930 - Not sure why I assumed pwd was the script dir.

---

just-mc.json
shared/fetch-tc-artifacts.sh

Download WPT MANIFEST.json for ingestion

---

shared/fetch-tc-artifacts.sh
shared/process-tc-artifacts.sh

Download SCIP files from taskcluster.

---

config2.json
config3.json

See individual commits for details

Bug 1836844 - Clean up config3 in preparation for new ESR

---

config1.json
just-mc.json
mozilla-central/build

This worked locally.  This does depend on the imminent re-provision.  I'll be checking in on things.

Bug 1426456 - Make scip-python work sufficiently

---

README.md
shared/collapse-generated-files.sh
shared/fetch-tc-artifacts.sh
shared/process-gecko-analysis.sh
shared/process-tc-artifacts.sh

Depends on https://phabricator.services.mozilla.com/D210841

Bug 1795177 - Fetch and process macos64-aarch64 artifacts.

---

comm-central/repo_files.py
kaios/repo_files.py
mozilla-beta/repo_files.py
mozilla-cedar/repo_files.py
mozilla-central/repo_files.py
mozilla-elm/repo_files.py
mozilla-esr102/repo_files.py
mozilla-esr115/repo_files.py
mozilla-esr17/repo_files.py
mozilla-esr31/repo_files.py
mozilla-esr45/repo_files.py
mozilla-esr60/repo_files.py
mozilla-esr68/repo_files.py
mozilla-esr78/repo_files.py
mozilla-esr91/repo_files.py
mozilla-release/repo_files.py

Same as HTML, indexing CSS inside WPT won't add much value right now.
required by https://github.com/mozsearch/mozsearch/pull/733

Exclude WPT from CSS indexing

---

comm-esr128/build
comm-esr128/reblame
comm-esr128/setup
comm-esr128/upload
config2.json
config3.json
help.html
mozilla-central/reblame
mozilla-central/setup
mozilla-esr128/build
mozilla-esr128/repo_files.py
mozilla-esr128/setup
mozilla-esr128/upload
shared/checkout-gecko-repos.sh

Bug 1901722 - Add esr128 repos

---

comm-central/repo_files.py
kaios/repo_files.py
mozilla-beta/repo_files.py
mozilla-cedar/repo_files.py
mozilla-central/repo_files.py
mozilla-elm/repo_files.py
mozilla-esr102/repo_files.py
mozilla-esr115/repo_files.py
mozilla-esr17/repo_files.py
mozilla-esr31/repo_files.py
mozilla-esr45/repo_files.py
mozilla-esr60/repo_files.py
mozilla-esr68/repo_files.py
mozilla-esr78/repo_files.py
mozilla-esr91/repo_files.py
mozilla-release/repo_files.py
wubkat/repo_files.py

for https://bugzilla.mozilla.org/show_bug.cgi?id=1416899
This does the following:
* add filter for webidl files, and filter out test files and also unused files
* add generated `CSS2Properties.webidl` to the list, in recent tree

Bug 1416899 - Add filter for WebIDL

---

config1.json
help.html
just-mozsearch.json
mozilla-central/build
mozsearch-mozilla/build
mozsearch-mozilla/reblame
mozsearch-mozilla/setup
mozsearch-mozilla/upload
mozsearch-tests/build
mozsearch-tests/reblame
mozsearch-tests/setup
mozsearch-tests/upload
mozsearch/build
mozsearch/reblame
mozsearch/setup
mozsearch/upload

Try run for config1.json with trees is up on asuth.searchfox.org :
- https://asuth.searchfox.org/mozsearch/source/
- https://asuth.searchfox.org/mozsearch-tests/source/
- https://asuth.searchfox.org/mozsearch-mozilla/source/

Bug 1858453 - Index mozsearch and mozsearch-mozilla

---

tree-list.js

for https://bugzilla.mozilla.org/show_bug.cgi?id=1672721
Almost same as the file for tests config, except for the test repositories group at the top.

Bug 1672721 - Part 1: Add tree-list.js

---

README.md
shared/collapse-generated-files.sh
shared/fetch-tc-artifacts.sh
shared/process-gecko-analysis.sh
shared/process-tc-artifacts.sh

This is currently up on kdab.searchfox.org using [this Try run](https://treeherder.mozilla.org/jobs?repo=try&revision=36722e667ecbdf459e69861ad735edb9f0677e65). This requires changes to m-c which I have not submitted for review yet, thus marking this as WIP.

Bug 1883953 - Add android-aarch64.

---

wubkat/build

There was some additional discussion in
https://github.com/mozsearch/mozsearch-mozilla/pull/262 of other changes we could make.  Since I'm landing a bunch of other updates, I'm making the changes now since I'll potentially need to investigate any fallout.

Bug 1912078 - Additional config changes proposed in #262 for config5

---

wubkat/build

Reverts mozsearch/mozsearch-mozilla#264

Revert "Bug 1912078 - Additional config changes proposed in #262 for config5"
